name: Destroy Saray_Server

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_DO_TOCKEN: ${{ secrets.DO_TOCKEN}}
  TF_VAR_MYSQL_DB: ${{ secrets.MYSQL_DB }}
  TF_VAR_MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  TF_VAR_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  TF_VAR_MYSQL_USER: ${{ secrets.MYSQL_USER }}
  TF_VAR_DOMAIN: ${{ secrets.DOMAIN }}
  TF_VAR_USER_EMAIL: ${{ secrets.USER_EMAIL }}
  
jobs:
  terraform-apply: 
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 01.9.8
          terraform_wrapper: false
      - name: Create SSH Keys from secrets
        run: |
          mkdir keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/saray_server
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/saray_server.pub
          chmod 777 ./keys/saray_server
          chmod 777 ./keys/saray_server.pub
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy
        run: terraform destroy --auto-approve